apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: livefox-cpu
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: livefox-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50