apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: livefox
  name: livefox-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
