---
apiVersion: v1
kind: Service
metadata:
        name: livefox-expose
        labels:
                app: livefox
spec:
        type: LoadBalancer
        ports:
                - port: 80
                  targetPort: 80
        selector:
                app: livefox
        externalIPs:
                - 10.10.50.100
        sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: livefox-deploy
        labels:
                app: livefox
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: livefox
        template:
                metadata:
                        labels:
                                app: livefox
                        annotations:
                                io.kubernetes.cri.untrusted-workload: "true"
                spec:
                        containers:
                                - name: livefox
                                  image: neopix/livefox:litearmv3
                                  ports:
                                          - containerPort: 2222
                                  volumeMounts:
                                          - mountPath: "/var/www/html/enc/"
                                            name: storage
                        volumes:
                                - name: storage
                                  emptyDir: {}
