---
apiVersion: v1
kind: Service
metadata:
        name: livefox-expose
        labels:
                app: livefox
spec:
        type: LoadBalancer
        ports:
                - port: 80
                  targetPort: 80
        selector:
                app: livefox
        externalIPs:
                - 10.0.2.7
        sessionAffinity: ClientIP
---
