apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: livefox_deployment
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: livefox.com
    http:
      paths:
      - path: /
        backend:
          serviceName: clientui-client
          servicePort: 8080
      - path: /upload
        backend:
          serviceName: mupload-client
          servicePort: 9002
