apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  backend:
    serviceName: livefox
    servicePort: 80

  rules:
  - host: livefox
    http:
      paths:
      - path: /
        backend:
          serviceName: clientui-client
          servicePort: 8080
      
      - path: /upload
        backend:
          serviceName: mupload-client
          servicePort: 9002
