---
    - hosts: <all in inventory>
      become: yes
      become_method: enable
      tasks:
        - name: update_cache
          become: yes
          become_method: sudo
          apt: 
            update_cache: yes

        - name: Install Docker for debian
          become: yes
          become_method: sudo
          apt: 
            name: "{{ packages }}"
            state: present
            update_cache: yes
          vars:
            packages:
                - apt-transport-https
                - ca-certificates
                - curl
                - gnupg-agent
                - software-properties-common

        - name: Execute the command in remote shell; install docker with curl command.
          become: yes
          become_method: sudo
          shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

        - name: update_cache
          become: yes
          become_method: sudo
          apt: 
            update_cache: yes

        - name: Install Docker 
          become: yes
          become_method: sudo
          apt: 
            name: "{{ packages }}"
            state: present
            update_cache: yes
          vars:
            packages:
                - docker-ce
                - docker-ce-cli
                - containerd.io     

        - name: Execute the command in remote shell; swapoff -a disable swarm for docker.
          become: yes
          become_method: sudo
          shell: swapoff -a